

development:
  adapter: mysql2
  database: rspec_development
  pool: 5
  username:
  password: happy1234

test:
  adapter: mysql2
  database: rspec_test
  pool: 5
  username:
  password: happy1234

production:
  adapter: mysql2
  database: rspec_production
  pool: 5
  username:
  password: happy1234
